### ISSUE TITLE
Ctrl-Tab is so slow and buggy when it is active

### ISSUE THREAD

**Issue by Archie-2021** [czottmann/obsidian-mononote#23]
Hello,

I was forced to deactivated this plugin because recently I found the reason my tab switching is so painfully slow (and it jumps in opposite direction) is because of this plugin. I guess it is checking something on every new tab change, but I don't think it is necessary. I only time it should check for a change is when I try to open something new. I hope this get fixed because I really like this plugin and think such a feature should be even built-in in Obsidian.

Thanks

**Comment by czottmann** [comment]
Thanks for the report, @Archie-2021. 

> I guess it is checking something on every new tab change, but I don't think it is necessary. I only time it should check for a change is when I try to open something new.

It does indeed but that's because Obsidian sends out notifications when the focus moves to another tab, and this is what Mononote hooks into. There's no way to filter the notifications beforehand, so Mononote has to react to every single one. This works better with a small number of open tabs, because the plugin needs to compare the currently active tab against all of them.

That said, I'm researching how to make the situation better but it's not as simple as it seems from the outside.

> [I] think such a feature should be even built-in in Obsidian

You and me, both 😉
