### ISSUE TITLE
For an EXcalidraw file, I want to treat its md mode and EXcalidraw mode as two files

### ISSUE THREAD

**Issue by jiajiala** [czottmann/obsidian-mononote#30]
When I click on some link in the EXcalidraw file that links to its own md text, an additional TAB opens to display it as an md file
After installing mononote, it is not available

**Comment by czottmann** [comment]
Hi, thanks for the report. I'm afraid I don't quite understand it fully yet.

You say _"After installing Mononote, it is not available"_ – do you mean that clicking a note link in an Excalidraw document doesn't open the note? And if so, how do get your Excalidraw docs into Obsidian in the first place?

**Comment by jiajiala** [comment]
![5](https://github.com/user-attachments/assets/0319c12e-a8c3-4d50-bcf4-c7c337beb3b9)
I installed the excalidraw plug-in, and then, like in the figure above, I click on the link to jump to the md pattern of excalidrawBut after installing mononote, you can't jump again
[Test-0711.md](https://github.com/user-attachments/files/17058482/Test-0711.md)
This is the sample file

**Comment by czottmann** [comment]
Thanks for the clarification! Yes, this is to be expected. `Test-0711.md` contains both the Markdown content and the Excalidraw content. In your example/GIF, you have `Test-0711` open in Excalidraw view, then click one of its embedded links, which opens _the same file_ but in Markdown view. That will not work as long as Mononote is active because it's **exactly** what it is trying to prevent. ;)

But even with Mononote enabled, you can still click links in the Excalidraw note which lead to other documents.

Hope this helps!
